channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - click=7.1.2
  - matplotlib=3.3.2
  - numba=0.51.2
  - numpy=1.19.2
  - python=3.8.6
  - pyyaml=5.3.1
  - r-base=3.6.3
  - r-dplyr=1.0.2
  - r-ggplot2=3.3.2
  - r-rcppcnpy=0.2.10
  - r-readr=1.4.0
  - r-stringr=1.4.0
  - r-tidyr=1.1.2
  - scipy=1.5.2