channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - bioconda::bcftools=1.17
  - conda-forge::click=7.1.2
  - conda-forge::matplotlib=3.3.2
  - conda-forge::numba=0.51.2
  - conda-forge::numpy=1.19.2
  - conda-forge::python=3.8.6
  - conda-forge::pyyaml=5.3.1
  - conda-forge::r-base=4.1.1
  - conda-forge::r-directlabels=2021.1.13
  - conda-forge::r-fs=1.6.2
  - conda-forge::r-rcppcnpy=0.2.11
  - conda-forge::r-styler=1.7.0
  - conda-forge::r-tidyverse=1.3.2
  - conda-forge::r-zoo=1.8_12
  - conda-forge::scipy=1.5.2